schemaVersion: 2.2.0
metadata:
  name: teleport
  version: '0.0.1'
  displayName: Teleport
projects:
  - name: teleport-web
    git:
      remotes:
        origin: 'https://github.com/sanjay-thiyagarajan/teleport_web.git'
      checkoutFrom:
        revision: main
  - name: teleport-rest
    git:
      remotes:
        origin: 'https://github.com/sanjay-thiyagarajan/teleport_rest.git'
      checkoutFrom:
        revision: main
components:
  - name: db
    container:
      image: mysql:latest
      env:
        - name: MYSQL_DATABASE
          value: 'teleportdb'
        - name: MYSQL_PASSWORD
          value: 'password'
        - name: MYSQL_ROOT_PASSWORD
          value: 'password'
      endpoints:
        - exposure: public
          name: db-3306
          protocol: http
          targetPort: 3306
  - name: teleport-rest
    container:
      image: python:latest
      env:
        - name: PYTHONUNBUFFERED
          value: '1'
