schemaVersion: 2.2.0
metadata:
  name: teleport
  version: '0.0.1'
  displayName: Teleport
projects:
  - name: teleport
    git:
      remotes:
        origin: 'https://github.com/sanjay-thiyagarajan/teleport.git'
      checkoutFrom:
        revision: main
