schemaVersion: 2.2.0
metadata:
  name: teleport
  version: '0.0.1'
  displayName: Teleport
projects:
  - name: teleport-web
    git:
      remotes:
        origin: 'https://github.com/sanjay-thiyagarajan/teleport_web.git'
      checkoutFrom:
        revision: main
  - name: teleport-rest
    git:
      remotes:
        origin: 'https://github.com/sanjay-thiyagarajan/teleport_rest.git'
      checkoutFrom:
        revision: main
components:
  - name: teleport-rest
    image:
      imageName: python3:latest
      autoBuild: true
      dockerfile:
        uri: docker/Dockerfile
        buildContext: .
        rootRequired: false
      
commands:
  - id: rest-install
    exec:
      commandLine: pip install -r requirements.txt
      component: teleport-rest
      workingDir: ./teleport_rest
      group:
        kind: build
        isDefault: true
  - id: rest-run
    exec:
      commandLine: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      component: teleport-rest
      workingDir: ./teleport_rest
      group:
        kind: run
        isDefault: true
  - id: deploy
    composite:
      commands:
      - rest-install
      - rest-run
      group:
        kind: deploy
        isDefault: true
