version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: teleport-db
    environment:
      MYSQL_DATABASE: 'teleportdb'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  teleport-rest:
    build: ./teleport_rest
    ports:
      - "8000:8000"
    container_name: teleport-rest
    command: >
        bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
  teleport-web:
    build: ./teleport_web
    ports:
      - "3000:3000"
    expose:
      - 3000
    container_name: teleport-web
    restart: always
    depends_on:
      - teleport-rest

volumes:
  my-db: