apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: teleport-rest
  name: teleport-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teleport-rest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: teleport-rest
    spec:
      containers:
        - args:
            - bash
            - -c
            - python manage.py migrate && python manage.py runserver 0.0.0.0:8000
          image: teleport-rest
          name: teleport-rest
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
