name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build REST image
      run: docker build ./teleport_rest --file ./teleport_rest/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build React image
      run: docker build ./teleport_web --file ./teleport_web/Dockerfile --tag my-image-name:$(date +%s)
